### ISSUE TITLE
Pre-slicing with a transform matrix leads to incorrect connections

### ISSUE THREAD

**Issue by tcstewar** [nengo-labs/nengo-ocl#175]
Ivana found a fascinating bug in nengo_ocl and I think I've tracked down a minimal example that causes it:

```
with nengo.Network() as model:
    stim = nengo.Node(lambda t: (1,0) if t<.5 else (0,1))
    result = nengo.Node(None, size_in=1)
    
    nengo.Connection(stim[0], result, transform=[[1]])
    nengo.Connection(stim[1], result, transform=[[1]])
    
    p_result = nengo.Probe(result)
    
with nengo.Simulator(model) as sim:
    sim.run(1.)
with nengo_ocl.Simulator(model) as sim_ocl:
    sim_ocl.run(1.)
```
The result should just be the sum of the two input values.  But here's what happens:
![image](https://user-images.githubusercontent.com/2380772/90305944-fdeecb00-de95-11ea-8e91-82388ec0b994.png)

We get very different behaviour in `nengo_ocl` than in `nengo`.

It looks to me like the second Connection is being interpretted as `stim[0]` instead of `stim[1]`.  IF you do more than 2, they all get interpretted as `stim[0]`.  If you change the transform to `1` instead of `[[1]]` this problem does not happen.

So my guess is it's something in the logic for combining the slice with the transform matrix.

**Comment by tcstewar** [comment]
As a quick update, it looks like this is fixed in the `nengo3` branch!   (I was testing with `nengo_ocl` master and `nengo` v2.8.0)

**Comment by drasmuss** [comment]
#172 is merged in now, so this should be fixed
