### ISSUE TITLE
Host documentation on nengo.ai

### ISSUE THREAD

**Issue by drasmuss** [nengo-labs/nengo-ocl#178]
The repo is already set up to generate rendered docs, we just need to upload those docs so they are hosted on nengo.ai

**Comment by tbekolay** [comment]
Hm... actually this is one tricky thing about moving repos to nengo-labs. I'll have to do a bit of looking into how this might work. We might end up hosting the docs at https://labs.nengo.ai/nengo-ocl or something like that if I can't point multiple Github repos to the same domain.

**Comment by drasmuss** [comment]
Yeah that doesn't seem like a bad thing in any case actually (to clearly differentiate docs for nengo-labs projects, which may not be as detailed/maintained as core projects)

**Comment by hunse** [comment]
Now online at https://labs.nengo.ai/nengo-ocl :1st_place_medal:
